"use client";

import { useMemo, useState } from "react";
import { ArrowRight, BookOpen, Bot, Boxes, ChevronRight, CircuitBoard, ExternalLink, Lightbulb, Menu, MousePointer2, Printer, Search, ShieldCheck, Sparkles, X, Zap } from "lucide-react";

type Stage = "Todos" | "Infantil" | "Primaria" | "Secundaria";

const materials = [
  { name:"mTiny Discover Kit", stage:"Infantil · 1.º–2.º Primaria", tags:["Infantil","Primaria"], lot:"Lote 1", icon:Bot, color:"#f3b51b", level:"Muy fácil", start:"Programa un recorrido con tarjetas para que mTiny visite tres lugares de un cuento.", learns:"Secuencias, orientación, narración y cooperación.", subjects:"Crecimiento en armonía · Descubrimiento del entorno · Lengua · Matemáticas", links:[{t:"Recursos mTiny",u:"https://education.makeblock.com/resource/mtiny/"}] },
  { name:"Floor Code Game", stage:"Infantil", tags:["Infantil"], lot:"Lote 3", icon:MousePointer2, color:"#ef6c63", level:"Muy fácil", start:"El alumnado se convierte en robot y sigue órdenes sobre un tablero grande.", learns:"Algoritmos corporales, lateralidad, secuencias y motricidad.", subjects:"Todas las áreas de Infantil · Psicomotricidad", links:[{t:"Plataforma E4CYL",u:"https://e4cyl.complubot.com/"}] },
  { name:"True True", stage:"1.º–4.º Primaria", tags:["Primaria"], lot:"Lote 3", icon:Bot, color:"#ed5e93", level:"Muy fácil", start:"Construye con tarjetas un recorrido por una cuadrícula de números, palabras o lugares.", learns:"Algoritmos, giros, depuración, sensores y eventos.", subjects:"Matemáticas · Lengua · Conocimiento del Medio · Artística", warning:"No utilizar cargadores de carga rápida.", links:[{t:"Cómo empezar",u:"https://www.truetrue.es/empezar.html"},{t:"Recursos imprimibles",u:"https://www.truetrue.es/recursos.html"},{t:"Recursos E4CYL",u:"https://e4cyl.complubot.com/truetrue.html"}] },
  { name:"Codey Rocky", stage:"3.º–6.º Primaria", tags:["Primaria"], lot:"Lote 1", icon:Bot, color:"#4bb3b7", level:"Fácil", start:"Conecta el robot a mBlock y programa luces, sonidos y un desplazamiento con condición.", learns:"Bloques, eventos, bucles, condicionales y sensores.", subjects:"Matemáticas · Conocimiento del Medio · Lengua · Artística", links:[{t:"mBlock online",u:"https://ide.mblock.cc/"},{t:"Recursos Makeblock",u:"https://education.makeblock.com/resource/codey-rocky/"}] },
  { name:"micro:bit V2 + sensores", stage:"3.º–6.º Primaria · ESO", tags:["Primaria","Secundaria"], lot:"Lote 3", icon:CircuitBoard, color:"#2f78c4", level:"Fácil", start:"Muestra un icono al pulsar un botón y después crea un contador o registra temperatura y luz.", learns:"Variables, datos, sensores, radio, bloques y Python.", subjects:"Matemáticas · Ciencias · Tecnología y Digitalización · Educación Física", links:[{t:"MakeCode",u:"https://makecode.microbit.org/"},{t:"Micro:bit Classroom",u:"https://classroom.microbit.org/"},{t:"Lecciones oficiales",u:"https://microbit.org/teach/lessons/"}] },
  { name:"SAM Labs", stage:"5.º–6.º Primaria · 1.º–3.º ESO", tags:["Primaria","Secundaria"], lot:"Lote 2", icon:Boxes, color:"#8a69c8", level:"Fácil", start:"Crea un sistema inalámbrico: entrada, regla y salida para resolver una necesidad del aula.", learns:"Sistemas, automatización, computación física y diseño.", subjects:"Ciencias · Tecnología · Matemáticas · Proyectos STEAM", links:[{t:"SAM Studio",u:"https://studio.samlabs.com/"},{t:"SAM Labs Europe",u:"https://samlabseurope.com/home45394246"},{t:"Web oficial SAM Labs",u:"https://samlabs.com/"}] },
  { name:"LEGO SPIKE Prime", stage:"5.º–6.º Primaria · 1.º–2.º ESO", tags:["Primaria","Secundaria"], lot:"Lote 3", icon:Boxes, color:"#ef6b36", level:"Intermedio", start:"Conoce hub, motores y sensores; construye una base móvil y haz que se detenga ante un obstáculo.", learns:"Diseño de ingeniería, mecanismos, sensores y programación.", subjects:"Matemáticas · Ciencias · Tecnología · Educación Física", links:[{t:"SPIKE online",u:"https://spike.legoeducation.com/prime/"},{t:"Unidades didácticas",u:"https://education.lego.com/en-us/teacher-resources/lego-education-spike-prime/lesson-planning/"},{t:"Recursos E4CYL",u:"https://e4cyl.complubot.com/lego-spike.html"}] },
  { name:"mBot2", stage:"1.º–4.º ESO", tags:["Secundaria"], lot:"Lote 1", icon:Bot, color:"#178d9b", level:"Intermedio", start:"Programa un recorrido preciso y añade respuesta a líneas, obstáculos o luz.", learns:"Robótica móvil, CyberPi, sensores, bloques y Python.", subjects:"Tecnología y Digitalización · Matemáticas · Física y Química", links:[{t:"Recursos mBot2",u:"https://education.makeblock.com/resource/mbot2/"},{t:"mBlock online",u:"https://ide.mblock.cc/"}] },
  { name:"Arduino UNO R4 WiFi", stage:"3.º–4.º ESO", tags:["Secundaria"], lot:"Lote 3", icon:CircuitBoard, color:"#217f78", level:"Avanzado", start:"Monta un LED con resistencia y programa su encendido; después incorpora un sensor.", learns:"Electrónica, C++, prototipado, automatización e IoT.", subjects:"Tecnología · Digitalización · Física y Química · Biología y Geología", warning:"Realizar el cableado siempre sin alimentación.", links:[{t:"Arduino UNO R4 WiFi",u:"https://docs.arduino.cc/hardware/uno-r4-wifi/"},{t:"Arduino Education",u:"https://www.arduino.cc/education"}] },
  { name:"Impresora 3D Creality K1C", stage:"ESO", tags:["Secundaria"], lot:"Lote 4", icon:Printer, color:"#3d6578", level:"Intermedio", start:"Diseña una pieza sencilla en Tinkercad, expórtala como STL y lamínala con Creality Print.", learns:"Diseño 3D, medida, prototipado y fabricación digital.", subjects:"Tecnología · Matemáticas · EPVA · Proyectos STEAM", warning:"Uso guiado; revisar laminado, cama y filamento antes de imprimir.", links:[{t:"Tinkercad",u:"https://www.tinkercad.com/"},{t:"Creality Print",u:"https://www.creality.com/pages/download-software"}] },
  { name:"Cortadora láser xTool M1", stage:"ESO", tags:["Secundaria"], lot:"Lote 4", icon:Zap, color:"#c5483d", level:"Avanzado", start:"Diseña una etiqueta o pieza plana y realiza una primera prueba sobre material autorizado.", learns:"Diseño vectorial, medida, prototipado y fabricación.", subjects:"Tecnología · EPVA · Matemáticas · Emprendimiento", warning:"Solo con supervisión, extracción/purificación activa y materiales autorizados.", links:[{t:"Centro de soporte xTool M1",u:"https://support.xtool.com/product/1"}] },
];

const curriculum = [
  ["3 años","Infantil","Crecimiento en armonía · Descubrimiento y exploración del entorno · Comunicación y representación","mTiny / Floor Code","Dar dos órdenes para llegar a un personaje; verbalizar delante/detrás."],
  ["4 años","Infantil","Las tres áreas de Infantil","mTiny / Floor Code","Secuenciar inicio–camino–meta sobre un cuento o rutina del aula."],
  ["5 años","Infantil","Las tres áreas de Infantil","mTiny / Floor Code","Crear, probar y corregir recorridos con símbolos y roles cooperativos."],
  ["1.º Primaria","Primaria","Matemáticas · Lengua · Conocimiento del Medio · Artística","mTiny / True True","Recorrer la recta numérica, ordenar una historia o visitar hábitats."],
  ["2.º Primaria","Primaria","Matemáticas · Lengua · Conocimiento del Medio · Artística","True True / mTiny","Sumas en cuadrícula, instrucciones escritas y mapas del entorno."],
  ["3.º Primaria","Primaria","Matemáticas · Lengua · Conocimiento del Medio · Artística","True True / Codey / micro:bit","Polígonos con recorridos, contador de hábitos o juego de preguntas."],
  ["4.º Primaria","Primaria","Matemáticas · Lengua · Ciencias · Artística","Codey / micro:bit / True True","Estación ambiental sencilla, animación dialogada o reto con sensores."],
  ["5.º Primaria","Primaria","Matemáticas · Ciencias · Lengua · Artística · Educación Física","micro:bit / SPIKE / SAM Labs","Registrar datos, construir una máquina o crear un podómetro."],
  ["6.º Primaria","Primaria","Matemáticas · Ciencias · Lengua · Artística · Educación Física","SPIKE / micro:bit / Codey / SAM Labs","Reto de ingeniería, experimento con sensores y defensa del prototipo."],
  ["1.º ESO","Secundaria","Tecnología y Digitalización · Matemáticas · Biología y Geología · EPVA","SPIKE / mBot2 / SAM Labs","Robot que resuelve una misión y documenta el proceso de diseño."],
  ["2.º ESO","Secundaria","Tecnología y Digitalización · Matemáticas · Física y Química · Biología","SPIKE / mBot2 / micro:bit","Medir una variable, representar datos y automatizar una respuesta."],
  ["3.º ESO","Secundaria","Tecnología y Digitalización · Matemáticas · Física y Química · Biología","Arduino / mBot2 / fabricación 3D","Invernadero con sensores, pieza funcional y memoria técnica."],
  ["4.º ESO","Secundaria","Digitalización · Tecnología · Matemáticas · Ciencias · Economía y Emprendimiento","Arduino / mBot2 / fabricación digital","Prototipo IoT o solución automatizada con presupuesto y presentación."],
];

const curriculumSubjects = [
  {stage:"Infantil", subject:"Descubrimiento y exploración del entorno", code:"Competencia específica 2", focus:"Desarrollar progresivamente el método científico y las destrezas del pensamiento computacional mediante la observación, la manipulación y la resolución creativa de retos.", criteria:["Planificar secuencias de actividades para afrontar retos y problemas.","Programar secuencias de acciones o instrucciones para resolver tareas analógicas y digitales.","Probar estrategias, tomar decisiones y aceptar el error como parte del aprendizaje."], contents:"Secuencias, nociones espaciales y temporales, relaciones causa–efecto, formulación de hipótesis y creación de soluciones.", classroom:"Recorridos con mTiny o Floor Code, instrucciones corporales, cuentos secuenciados y retos de orientación.", source:"Decreto 37/2022"},
  {stage:"Primaria", subject:"Conocimiento del Medio Natural, Social y Cultural", code:"Competencia específica 3", focus:"Resolver problemas mediante proyectos de diseño y pensamiento computacional para crear cooperativamente un producto que responda a una necesidad concreta.", criteria:["1.º ciclo: participar en problemas sencillos de programación y explicar el prototipo.","2.º ciclo: modificar algoritmos de forma guiada y probar distintas soluciones.","3.º ciclo: detectar necesidades, diseñar, prototipar, evaluar y comunicar una solución digital."], contents:"Programación desenchufada y por bloques, robótica educativa, sensores, motores, simuladores, prototipado y trabajo cooperativo.", classroom:"Robot para explicar un ecosistema, estación ambiental con micro:bit o prototipo que mejore algún aspecto del centro.", source:"Decreto 38/2022"},
  {stage:"Primaria", subject:"Matemáticas", code:"Competencia específica 4", focus:"Utilizar el pensamiento computacional organizando datos, descomponiendo problemas, reconociendo patrones y creando algoritmos para modelizar situaciones cotidianas.", criteria:["1.º ciclo: describir rutinas e instrucciones ordenadas paso a paso.","2.º ciclo: interpretar y modificar algoritmos con secuencias, bucles y patrones.","3.º ciclo: modelizar situaciones y crear algoritmos con instrucciones anidadas y condicionales."], contents:"Sentido algebraico: algoritmos, patrones, secuencias, bucles y condicionales. Sentido espacial: cuadrículas, geometría dinámica y robótica.", classroom:"Recorridos geométricos con True True, contador con micro:bit o reto de distancias y giros con SPIKE.", source:"Decreto 38/2022"},
  {stage:"Secundaria", subject:"Matemáticas", code:"Competencia específica 4", focus:"Organizar datos, descomponer problemas, reconocer patrones e interpretar, modificar y crear algoritmos para modelizar y resolver problemas.", criteria:["1.º–3.º ESO: reconocer patrones, organizar datos y descomponer problemas.","Interpretar y modificar algoritmos para construir modelos eficaces.","4.º ESO: crear, generalizar y analizar algoritmos y representaciones computacionales."], contents:"Sentido algebraico: automatización, pensamiento algorítmico, interpretación y creación de algoritmos y análisis de problemas mediante programas.", classroom:"Programar ecuaciones con SPIKE, analizar datos de sensores o diseñar un algoritmo para optimizar un recorrido.", source:"Decreto 39/2022"},
  {stage:"Secundaria", subject:"Biología y Geología", code:"Competencia específica 4", focus:"Usar razonamiento lógico y pensamiento computacional para resolver problemas o explicar procesos biológicos y geológicos, revisando el procedimiento cuando sea necesario.", criteria:["Resolver problemas utilizando conocimientos, datos, pensamiento computacional y recursos digitales.","Analizar críticamente la solución y reformularla cuando no sea viable o aparezcan nuevos datos."], contents:"Proyecto científico: hipótesis, toma y análisis de datos, modelización de procesos naturales y comunicación digital de resultados.", classroom:"Invernadero automatizado, registro ambiental con sensores o modelo programado de una cadena trófica.", source:"Decreto 39/2022"},
  {stage:"Secundaria", subject:"Tecnología y Digitalización · 1.º–3.º ESO", code:"Competencias específicas 3 y 5", focus:"Diseñar y fabricar soluciones tecnológicas y desarrollar algoritmos y aplicaciones para automatizar procesos, sistemas de control y robots.", criteria:["Diseñar algoritmos y diagramas de flujo.","Programar aplicaciones sencillas e incorporar tecnologías emergentes.","Construir y programar robots y sistemas automáticos, conectados o simulados."], contents:"Algoritmia, programación, inteligencia artificial, sistemas de control, internet de las cosas, robótica, depuración y fabricación digital.", classroom:"Robot autónomo con mBot2, sistema con SAM Labs o control de sensores y actuadores con micro:bit.", source:"Decreto 39/2022"},
  {stage:"Secundaria", subject:"Tecnología · 4.º ESO", code:"Competencias específicas 2 y 4", focus:"Fabricar soluciones tecnológicas sostenibles y desarrollar sistemas automáticos programables y robóticos incorporando tecnologías emergentes.", criteria:["Diseñar, construir, controlar o simular sistemas automáticos y robots.","Integrar IoT, inteligencia artificial y simulación con sentido crítico y ético.","Fabricar productos mediante diseño asistido y técnicas manuales, mecánicas y digitales."], contents:"Controladores, sensores, actuadores, simulación, IoT, robótica, diseño y fabricación digital.", classroom:"Invernadero con Arduino, sistema domótico o pieza funcional diseñada e impresa en 3D.", source:"Decreto 39/2022"},
  {stage:"Secundaria", subject:"Digitalización · 4.º ESO", code:"Competencia específica 2", focus:"Configurar el entorno personal de aprendizaje y crear, programar, integrar y reelaborar contenidos digitales de manera autónoma, creativa y responsable.", criteria:["Crear y programar contenidos digitales seleccionando las herramientas adecuadas.","Colaborar y publicar información adaptada a distintas audiencias.","Aplicar criterios de autoría, seguridad, ética y uso responsable de los datos."], contents:"Aplicaciones sencillas para web y móvil, realidad virtual y aumentada, colaboración en red, IA, sesgos algorítmicos y ciudadanía digital.", classroom:"Experiencia de realidad virtual, aplicación sencilla o análisis crítico de decisiones algorítmicas.", source:"Decreto 39/2022"},
];

const thinkingSkills = [
  ["Descomponer","Dividir un reto complejo en partes pequeñas y manejables."],
  ["Reconocer patrones","Localizar regularidades y aprovechar soluciones que ya funcionan."],
  ["Abstraer","Quedarse con la información relevante y apartar lo que no ayuda."],
  ["Diseñar algoritmos","Expresar una solución mediante pasos claros, ordenados y finitos."],
  ["Evaluar y depurar","Comprobar el resultado, localizar errores y mejorar el procedimiento."],
  ["Generalizar","Transferir lo aprendido a problemas y contextos nuevos."],
];

const progression = [
  ["1.º–2.º Primaria","Ordena instrucciones, juega a ser un robot y crea secuencias sencillas con ayuda."],
  ["3.º–4.º Primaria","Crea y modifica programas por bloques; prueba soluciones y explica sus decisiones."],
  ["5.º–6.º Primaria","Combina programación, robótica y sensores para resolver retos concretos de forma creativa."],
  ["1.º–2.º ESO","Interpreta algoritmos y utiliza entornos de programación para tareas cada vez más variadas."],
  ["3.º–4.º ESO","Desarrolla aplicaciones y soluciones tecnológicas creativas, sostenibles y con sentido ético."],
];

export default function Home(){
  const basePath=process.env.NEXT_PUBLIC_BASE_PATH??"";
  const [stage,setStage]=useState<Stage>("Todos"); const [query,setQuery]=useState(""); const [menu,setMenu]=useState(false);
  const shown=useMemo(()=>materials.filter(m=>(stage==="Todos"||m.tags.includes(stage))&&(m.name+m.subjects+m.stage).toLowerCase().includes(query.toLowerCase())),[stage,query]);
  return <main>
    <header className="topbar"><a href="#inicio" className="brand"><img src={`${basePath}/pegatina-escuela-40.png`} alt="Código Escuela 4.0 Castilla y León"/><span>Guía de aula</span></a><button className="menuButton" onClick={()=>setMenu(!menu)} aria-label="Abrir navegación">{menu?<X/>:<Menu/>}</button><nav className={menu?"nav open":"nav"}><a href="#pensamiento">Pensamiento computacional (PC)</a><a href="#empezar">Empieza aquí</a><a href="#materiales">Recursos</a><a href="#curriculo">Currículo</a></nav></header>
    <section id="inicio" className="hero"><div className="heroText"><div className="eyebrow"><Sparkles size={16}/> Código Escuela 4.0 · León</div><h1>Escuela 4.0<br/>en el aula</h1><p>Elige un recurso, descubre una actividad y llévala al aula.</p><div className="heroActions"><a className="primary" href="#empezar">Quiero empezar <ArrowRight size={18}/></a><a className="secondary" href="#curriculo">Ver por curso</a></div></div><div className="pathCard" aria-label="Itinerario de aprendizaje"><p className="cardLabel">Un itinerario progresivo</p>{[["01","Explora","Sin pantallas · Infantil"],["02","Programa","Bloques y robots · Primaria"],["03","Construye","Sensores y mecanismos"],["04","Prototipa","Electrónica y fabricación · ESO"]].map(x=><div className="pathStep" key={x[0]}><span>{x[0]}</span><div><b>{x[1]}</b><small>{x[2]}</small></div></div>)}</div></section>
    <section id="pensamiento" className="section thinking"><div className="sectionHeading"><span className="kicker">Antes de programar</span><h2>Pensamiento computacional, en pocas palabras</h2><p>Es una forma de formular y resolver problemas para que la solución pueda ser comprendida y ejecutada por una persona o una máquina. Se apoya en ideas de la informática, pero es transferible a cualquier materia.</p></div><div className="notSame"><div><span>La forma de pensar</span><h3>Pensamiento computacional</h3><p>Analizar, representar y resolver un problema de manera lógica y reutilizable. También se trabaja sin pantallas: con historias, recorridos, tarjetas, construcciones o juegos.</p></div><div><span>Una manera de expresarlo</span><h3>Programación</h3><p>Escribir una solución con las reglas de un lenguaje para que la ejecute un dispositivo. Ayuda a desarrollar el pensamiento computacional, pero no son sinónimos.</p></div><div><span>Un contexto para probarlo</span><h3>Robótica</h3><p>Combinar programa, sensores, motores y mecanismos para actuar en el mundo físico. Hace visibles las decisiones y facilita comprobar y depurar.</p></div></div><div className="skillsGrid">{thinkingSkills.map((skill,i)=><article key={skill[0]}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{skill[0]}</h3><p>{skill[1]}</p></div></article>)}</div><div className="progression"><div className="progressionIntro"><span className="kicker">Progresión orientativa</span><h3>De seguir una secuencia a crear una solución</h3><p>La complejidad crece poco a poco. En cada etapa importa que el alumnado explique, pruebe y mejore, no solo que el dispositivo funcione.</p></div><ol>{progression.map(item=><li key={item[0]}><b>{item[0]}</b><p>{item[1]}</p></li>)}</ol></div></section>
    <section id="empezar" className="section startSection"><div className="sectionHeading"><span className="kicker">Antes de abrir la caja</span><h2>Tu primera sesión, en cuatro decisiones</h2><p>No hace falta dominar la robótica. Empieza con un objetivo curricular pequeño y deja que el alumnado pruebe, explique y corrija.</p></div><div className="steps">{[["1","Elige un aprendizaje","Una secuencia, una medida, una historia o un problema real."],["2","Prueba lo mínimo","Carga, conecta y ejecuta un único ejemplo antes de la clase."],["3","Trabaja por equipos","Roles: programación, montaje, comprobación y documentación."],["4","Evalúa el proceso","Observa planificación, cooperación, prueba y depuración; no solo el resultado."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><div className="tip"><Lightbulb/><p><b>Sesión inicial recomendada:</b> 10 min de demostración, 25 min de reto en equipos y 10 min para compartir qué funcionó, qué falló y cómo lo corrigieron.</p></div></section>
    <section id="materiales" className="section alt"><div className="sectionHeading"><span className="kicker">Presentación de materiales</span><h2>Encuentra el recurso adecuado</h2><p>Filtra por etapa y abre solo lo que necesitas: primera actividad, aprendizajes, materias y enlaces oficiales.</p></div><div className="filters"><div className="stageFilters">{(["Todos","Infantil","Primaria","Secundaria"] as Stage[]).map(s=><button className={stage===s?"active":""} onClick={()=>setStage(s)} key={s}>{s}</button>)}</div><label className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar material o materia"/></label></div><div className="materialGrid">{shown.map(m=>{const Icon=m.icon;return <article className="materialCard" key={m.name} style={{"--accent":m.color} as React.CSSProperties}><div className="materialTop"><span className="icon"><Icon/></span><span className="lot">{m.lot}</span></div><p className="stage">{m.stage}</p><h3>{m.name}</h3><div className="level"><span/> Inicio: {m.level}</div><details><summary>Ver guía rápida <ChevronRight size={17}/></summary><div className="detailsBody"><b>Primera actividad</b><p>{m.start}</p><b>Qué se trabaja</b><p>{m.learns}</p><b>Materias / áreas</b><p>{m.subjects}</p>{m.warning&&<p className="warning"><ShieldCheck size={16}/>{m.warning}</p>}<div className="cardLinks">{m.links.map(l=><a href={l.u} target="_blank" rel="noreferrer" key={l.u}>{l.t}<ExternalLink size={14}/></a>)}</div></div></details></article>})}</div></section>
    <section id="curriculo" className="section curriculum"><div className="sectionHeading"><span className="kicker">Vinculación curricular LOMLOE</span><h2>Una idea para cada curso</h2><p>Orientación práctica basada en los currículos de Castilla y León y en la presentación aportada sobre robótica educativa. Selecciona etapa para reducir la tabla y consultar la vinculación de cada materia.</p></div><div className="curriculumKey"><b>Cómo leer esta vinculación</b><p><strong>Relación directa:</strong> el currículo nombra pensamiento computacional, programación o robótica. <strong>Relación transversal:</strong> el área permite trabajarlos mediante proyectos, diseño de soluciones, datos o resolución de problemas, aunque no siempre los cite de forma expresa.</p></div><div className="stageFilters curriculumFilters">{(["Todos","Infantil","Primaria","Secundaria"] as Stage[]).map(s=><button className={stage===s?"active":""} onClick={()=>setStage(s)} key={s}>{s}</button>)}</div><div className="tableWrap"><table><thead><tr><th>Curso</th><th>Áreas / materias</th><th>Material recomendado</th><th>Propuesta de partida</th></tr></thead><tbody>{curriculum.filter(r=>stage==="Todos"||r[1]===stage).map(r=><tr key={r[0]}><td><b>{r[0]}</b><small>{r[1]}</small></td><td>{r[2]}</td><td>{r[3]}</td><td>{r[4]}</td></tr>)}</tbody></table></div><div className="curriculumDetail"><div className="curriculumTitle"><span className="kicker">Qué recoge el currículo</span><h3>Pensamiento computacional por materia</h3><p>Abre cada materia para ver la competencia, los criterios relacionados, los contenidos y una forma concreta de llevarlos al aula.</p></div><div className="curriculumCards">{curriculumSubjects.filter(item=>stage==="Todos"||item.stage===stage).map(item=><details className="curriculumCard" key={item.subject}><summary><div><span>{item.stage}</span><h4>{item.subject}</h4><small>{item.code}</small></div><ChevronRight/></summary><div className="curriculumBody"><div className="curriculumFocus"><b>Competencia relacionada</b><p>{item.focus}</p></div><div className="curriculumColumns"><div><b>Criterios y progresión</b><ul>{item.criteria.map(criterion=><li key={criterion}>{criterion}</li>)}</ul></div><div><b>Contenidos vinculados</b><p>{item.contents}</p><b>Ejemplo de aplicación</b><p>{item.classroom}</p></div></div><div className="curriculumSource"><BookOpen size={15}/>{item.source} · Currículo de Castilla y León</div></div></details>)}</div></div><p className="legalNote"><BookOpen size={17}/> En Infantil la relación directa se concentra en Descubrimiento y exploración del entorno. En Primaria destaca Ciencias Naturales; Matemáticas aborda el pensamiento computacional y Ciencias Sociales permite una conexión principalmente mediante proyectos. La concreción final debe adaptarse al curso y a la programación del centro.</p></section>
    <footer><img src={`${basePath}/logos-escuela-40.png`} alt="Gobierno de España, Código Escuela 4.0 y Junta de Castilla y León"/><div><b>Guía práctica Escuela 4.0 · León</b><p>Recurso de orientación docente. Los enlaces externos pueden actualizarse por sus entidades responsables.</p></div><a href="#inicio">Volver arriba ↑</a></footer>
  </main>
}
